var LIST_CITIES = [
    "Acton",
    "Adelanto",
    "Agoura Hills",
    "Alameda",
    "Alamo",
    "Albany",
    "Alhambra",
    "Aliso Viejo",
    "Almanor",
    "Alondra Park",
    "Alpaugh",
    "Alpine",
    "Alpine Village",
    "Alta Sierra",
    "Altadena",
    "Alturas",
    "Alum Rock",
    "Amador City",
    "American Canyon",
    "Amesti",
    "Anaheim",
    "Anderson",
    "Angels City",
    "Angwin",
    "Antioch",
    "Apple Valley",
    "Aptos",
    "Aptos Hills-Larkin Valley",
    "Arbuckle",
    "Arcadia",
    "Arcata",
    "Arden-Arcade",
    "Armona",
    "Arnold",
    "Aromas",
    "Arroyo Grande",
    "Artesia",
    "Arvin",
    "Ashland",
    "Atascadero",
    "Atherton",
    "Atwater",
    "Auberry",
    "Auburn",
    "August",
    "Avalon",
    "Avenal",
    "Avery",
    "Avocado Heights",
    "Azusa",
    "Bakersfield",
    "Baldwin Park",
    "Banning",
    "Barstow",
    "Bay Point",
    "Bayview",
    "Bayview-Montalvin",
    "Baywood-Los Osos",
    "Beale AFB",
    "Bear Valley",
    "Bear Valley Springs",
    "Beaumont",
    "Beckwourth",
    "Belden",
    "Bell",
    "Bell Gardens",
    "Bellflower",
    "Belmont",
    "Belvedere",
    "Ben Lomond",
    "Benicia",
    "Berkeley",
    "Bermuda Dunes",
    "Bertsch-Oceanview",
    "Bethel Island",
    "Beverly Hills",
    "Big Bear City",
    "Big Bear Lake",
    "Big Bend",
    "Big Pine",
    "Big River",
    "Biggs",
    "Biola",
    "Bishop",
    "Black Point-Green Point",
    "Blackhawk-Camino Tassajara",
    "Blairsden",
    "Bloomington",
    "Blue Lake",
    "Bluewater",
    "Blythe",
    "Bodega Bay",
    "Bodfish",
    "Bolinas",
    "Bombay Beach",
    "Bonadelle Ranchos-Madera Ranchos",
    "Bonita",
    "Bonsall",
    "Bootjack",
    "Boron",
    "Boronda",
    "Borrego Springs",
    "Bostonia",
    "Boulder Creek",
    "Bowles",
    "Boyes Hot Springs",
    "Bradbury",
    "Bradley",
    "Brawley",
    "Brea",
    "Brentwood",
    "Bret Harte",
    "Brisbane",
    "Broadmoor",
    "Bucks Lake",
    "Buellton",
    "Buena Park",
    "Buena Vista",
    "Burbank",
    "Burbank_sj",
    "Burlingame",
    "Burney",
    "Buttonwillow",
    "Byron",
    "Bystrom",
    "Cabazon",
    "Calabasas",
    "Calexico",
    "California City",
    "Calimesa",
    "Calipatria",
    "Calistoga",
    "Calwa",
    "Camarillo",
    "Cambria",
    "Cambrian Park",
    "Cameron Park",
    "Camp Pendleton North",
    "Camp Pendleton South",
    "Campbell",
    "Cantua Creek",
    "Canyon Lake",
    "Canyondam",
    "Capitola",
    "Caribou",
    "Carlsbad",
    "Carmel Valley Village",
    "Carmel-by-the-Sea",
    "Carmichael",
    "Carpinteria",
    "Carrick",
    "Carson",
    "Cartago",
    "Caruthers",
    "Casa Conejo",
    "Casa de Oro-Mount Helix",
    "Castro Valley",
    "Castroville",
    "Cathedral City",
    "Cayucos",
    "Ceres",
    "Cerritos",
    "Challenge-Brownsville",
    "Channel Islands Beach",
    "Charter Oak",
    "Cherry Valley",
    "Cherryland",
    "Chester",
    "Chico",
    "Chilcoot-Vinton",
    "China Lake Acres",
    "Chinese Camp",
    "Chino",
    "Chino Hills",
    "Chowchilla",
    "Chualar",
    "Chula Vista",
    "Citrus",
    "Citrus Heights",
    "Claremont",
    "Clayton",
    "Clearlake",
    "Clearlake Oaks",
    "Clio",
    "Cloverdale",
    "Clovis",
    "Clyde",
    "Coachella",
    "Coalinga",
    "Cobb",
    "Colfax",
    "Colma",
    "Colton",
    "Columbia",
    "Colusa",
    "Commerce",
    "Compton",
    "Concord",
    "Concow",
    "Copperopolis",
    "Corcoran",
    "Corning",
    "Corona",
    "Coronado",
    "Corralitos",
    "Corte Madera",
    "Costa Mesa",
    "Cotati",
    "Coto de Caza",
    "Cottonwood",
    "Country Club",
    "Covelo",
    "Covina",
    "Crescent City",
    "Crescent City North",
    "Crescent Mills",
    "Crest",
    "Crestline",
    "Crockett",
    "Cromberg",
    "Cudahy",
    "Culver City",
    "Cupertino",
    "Cutler",
    "Cutten",
    "Cypress",
    "Daly City",
    "Dana Point",
    "Danville",
    "Darwin",
    "Davis",
    "Day Valley",
    "Deer Park",
    "Del Aire",
    "Del Mar",
    "Del Monte Forest",
    "Del Rey",
    "Del Rey Oaks",
    "Del Rio",
    "Delano",
    "Delhi",
    "Delleker",
    "Denair",
    "Derby Acres",
    "Desert Hot Springs",
    "Desert Shores",
    "Desert View Highlands",
    "Diablo",
    "Diamond Bar",
    "Diamond Springs",
    "Dillon Beach",
    "Dinuba",
    "Discovery Bay",
    "Dixon",
    "Dixon Lane-Meadow Creek",
    "Dollar Point",
    "Dorrington",
    "Dorris",
    "Dos Palos",
    "Downey",
    "Duarte",
    "Dublin",
    "Ducor",
    "Dunsmuir",
    "Durham",
    "Dustin Acres",
    "Earlimart",
    "East Blythe",
    "East Compton",
    "East Foothills",
    "East Hemet",
    "East La Mirada",
    "East Los Angeles",
    "East Oakdale",
    "East Orosi",
    "East Palo Alto",
    "East Pasadena",
    "East Porterville",
    "East Quincy",
    "East Richmond Heights",
    "East San Gabriel",
    "East Shore",
    "East Sonora",
    "Easton",
    "Edgewood",
    "Edwards AFB",
    "El Cajon",
    "El Centro",
    "El Cerito_la",
    "El Cerrito",
    "El Dorado Hills",
    "El Granada",
    "El Monte",
    "El Paso de Robles (Paso Robles)",
    "El Rio",
    "El Segundo",
    "El Sobrante",
    "El Verano",
    "Eldridge",
    "Elk Grove",
    "Elkhorn",
    "Elmira",
    "Emerald Lake Hills",
    "Emeryville",
    "Empire",
    "Encinitas",
    "Escalon",
    "Escondido",
    "Esparto",
    "Etna",
    "Eureka",
    "Exeter",
    "Fair Oaks",
    "Fairbanks Ranch",
    "Fairfax",
    "Fairfield",
    "Fairview",
    "Fall River Mills",
    "Fallbrook",
    "Farmersville",
    "Farmington",
    "Fellows",
    "Felton",
    "Ferndale",
    "Fetters Hot Springs-Agua Caliente",
    "Fillmore",
    "Firebaugh",
    "Florence-Graham",
    "Florin",
    "Folsom",
    "Fontana",
    "Foothill Farms",
    "Foothill Ranch",
    "Ford City",
    "Forest Meadows",
    "Foresthill",
    "Forestville",
    "Fort Bragg",
    "Fort Jones",
    "Fortuna",
    "Foster City",
    "Fountain Valley",
    "Fowler",
    "Frazier Park",
    "Freedom",
    "Fremont",
    "French Camp",
    "French Gulch",
    "Fresno",
    "Friant",
    "Fruitdale",
    "Fullerton",
    "Furnace Creek",
    "Galt",
    "Garden Acres",
    "Garden Grove",
    "Gardena",
    "Gazelle",
    "Georgetown",
    "Gerber-Las Flores",
    "Gilroy",
    "Glen Avon",
    "Glen Ellen",
    "Glendale",
    "Glendora",
    "Gold River",
    "Golden Hills",
    "Goleta",
    "Gonzales",
    "Goshen",
    "Graeagle",
    "Grand Terrace",
    "Granite Bay",
    "Granite Hills",
    "Grass Valley",
    "Graton",
    "Grayson",
    "Green Valley",
    "Greenfield",
    "Greenhorn",
    "Greenview",
    "Greenville",
    "Grenada",
    "Gridley",
    "Groveland-Big Oak Flat",
    "Grover Beach",
    "Guadalupe",
    "Guerneville",
    "Gustine",
    "Hacienda Heights",
    "Half Moon Bay",
    "Hamilton Branch",
    "Hamilton City",
    "Hanford",
    "Harbison Canyon",
    "Hawaiian Gardens",
    "Hawthorne",
    "Hayfork",
    "Hayward",
    "Healdsburg",
    "Heber",
    "Hemet",
    "Hercules",
    "Hermosa Beach",
    "Hesperia",
    "Hickman",
    "Hidden Hills",
    "Hidden Meadows",
    "Hidden Valley Lake",
    "Highgrove",
    "Highland",
    "Highlands-Baywood Park",
    "Hillsborough",
    "Hilmar-Irwin",
    "Hollister",
    "Holtville",
    "Home Garden",
    "Home Gardens",
    "Homeland",
    "Homewood Canyon-Valley Wells",
    "Hornbrook",
    "Hughson",
    "Humboldt Hill",
    "Huntington Beach",
    "Huntington Park",
    "Huron",
    "Hydesville",
    "Idyllwild-Pine Cove",
    "Imperial",
    "Imperial Beach",
    "Independence",
    "Indian Falls",
    "Indian Wells",
    "Indio",
    "Industry",
    "Inglewood",
    "Interlaken",
    "Inverness",
    "Inyokern",
    "Ione",
    "Iron Horse",
    "Irvine",
    "Irwindale",
    "Isla Vista",
    "Isleton",
    "Ivanhoe",
    "Jackson",
    "Jamestown",
    "Jamul",
    "Johannesburg",
    "Johnsville",
    "Joshua Tree",
    "Julian",
    "Keddie",
    "Keeler",
    "Keene",
    "Kelseyville",
    "Kennedy",
    "Kensington",
    "Kentfield",
    "Kerman",
    "Kernville",
    "Kettleman City",
    "Keyes",
    "King City",
    "Kings Beach",
    "Kingsburg",
    "Kirkwood",
    "Klamath",
    "Knightsen",
    "La Canada Flintridge",
    "La Crescenta-Montrose",
    "La Habra",
    "La Habra Heights",
    "La Mesa",
    "La Mirada",
    "La Palma",
    "La Porte",
    "La Presa",
    "La Puente",
    "La Quinta",
    "La Riviera",
    "La Verne",
    "Ladera Heights",
    "Lafayette",
    "Laguna",
    "Laguna Beach",
    "Laguna Hills",
    "Laguna Niguel",
    "Laguna West-Lakeside",
    "Laguna Woods",
    "Lagunitas-Forest Knolls",
    "Lake Almanor Country Club",
    "Lake Almanor Peninsula",
    "Lake Almanor West",
    "Lake Arrowhead",
    "Lake Davis",
    "Lake Elsinore",
    "Lake Forest",
    "Lake Isabella",
    "Lake Los Angeles",
    "Lake Nacimiento",
    "Lake San Marcos",
    "Lake Wildwood",
    "Lake of the Pines",
    "Lake of the Woods",
    "Lakehead-Lakeshore",
    "Lakeland Village",
    "Lakeport",
    "Lakeside",
    "Lakeview",
    "Lakewood",
    "Lamont",
    "Lanare",
    "Lancaster",
    "Larkfield-Wikiup",
    "Larkspur",
    "Las Flores",
    "Las Lomas",
    "Lathrop",
    "Laton",
    "Lawndale",
    "Laytonville",
    "Le Grand",
    "Lebec",
    "Lemon Cove",
    "Lemon Grove",
    "Lemoore",
    "Lemoore Station",
    "Lennox",
    "Lenwood",
    "Lewiston",
    "Lexington Hills",
    "Lincoln",
    "Lincoln  Village",
    "Linda",
    "Linden",
    "Lindsay",
    "Little Grass Valley",
    "Littlerock",
    "Live Oak",
    "Live Oak -CV",
    "Livermore",
    "Livingston",
    "Lockeford",
    "Lodi",
    "Loma Linda",
    "Loma Rica",
    "Lomita",
    "Lompoc",
    "London",
    "Lone Pine",
    "Long Beach",
    "Loomis",
    "Los Alamitos",
    "Los Alamos",
    "Los Altos",
    "Los Altos Hills",
    "Los Angeles",
    "Los Banos",
    "Los Gatos",
    "Los Molinos",
    "Lost Hills",
    "Lower Lake",
    "Loyalton",
    "Loyola",
    "Lucas Valley-Marinwood",
    "Lucerne",
    "Lynwood",
    "Macdoel",
    "Madera",
    "Madera Acres",
    "Magalia",
    "Malibu",
    "Mammoth Lakes",
    "Manhattan Beach",
    "Manteca",
    "Manton",
    "March AFB",
    "Maricopa",
    "Marina",
    "Marina del Rey",
    "Mariposa",
    "Markleeville",
    "Martinez",
    "Marysville",
    "Mayflower Village",
    "Maywood",
    "McArthur",
    "McCloud",
    "McFarland",
    "McKinleyville",
    "McKittrick",
    "Meadow Valley",
    "Meadow Vista",
    "Mecca",
    "Meiners Oaks",
    "Mendocino",
    "Mendota",
    "Menlo Park",
    "Mentone",
    "Merced",
    "Mesa",
    "Mesa Vista",
    "Mettler",
    "Mi-Wuk Village",
    "Middletown",
    "Mill Valley",
    "Millbrae",
    "Millville",
    "Milpitas",
    "Mineral",
    "Mira Loma",
    "Mira Monte",
    "Mission Canyon",
    "Mission Hills",
    "Mission Viejo",
    "Modesto",
    "Mohawk Vista",
    "Mojave",
    "Mokelumne Hill",
    "Mono Vista",
    "Monrovia",
    "Montague",
    "Montara",
    "Montclair",
    "Monte Rio",
    "Monte Sereno",
    "Montebello",
    "Montecito",
    "Monterey",
    "Monterey Park",
    "Montgomery Creek",
    "Moorpark",
    "Morada",
    "Moraga",
    "Moreno Valley",
    "Morgan Hill",
    "Morongo Valley",
    "Morro Bay",
    "Moss Beach",
    "Moss Landing",
    "Mount Hebron",
    "Mount Shasta",
    "Mountain Mesa",
    "Mountain Ranch",
    "Mountain View",
    "Mountain View Acres",
    "Muir Beach",
    "Murphys",
    "Murrieta",
    "Murrieta Hot Springs",
    "Muscoy",
    "Myrtletown",
    "Napa",
    "National City",
    "Nebo Center",
    "Needles",
    "Nevada City",
    "Newark",
    "Newman",
    "Newport Beach",
    "Newport Coast",
    "Nice",
    "Niland",
    "Nipomo",
    "Norco",
    "North Auburn",
    "North Edwards",
    "North El Monte",
    "North Fair Oaks",
    "North Highlands",
    "North Lakeport",
    "North Woodbridge",
    "Norwalk",
    "Novato",
    "Nuevo",
    "Oak Park",
    "Oak View",
    "Oakdale",
    "Oakhurst",
    "Oakland",
    "Oakley",
    "Occidental",
    "Oceano",
    "Oceanside",
    "Ocotillo",
    "Oildale",
    "Ojai",
    "Olancha",
    "Olivehurst",
    "Ontario",
    "Onyx",
    "Opal Cliffs",
    "Orange",
    "Orange Cove",
    "Orangevale",
    "Orcutt",
    "Orinda",
    "Orland",
    "Orosi",
    "Oroville",
    "Oroville East",
    "Oxnard",
    "Pacheco",
    "Pacific Grove",
    "Pacifica",
    "Pajaro",
    "Palermo",
    "Palm Desert",
    "Palm Springs",
    "Palmdale",
    "Palo Alto",
    "Palo Cedro",
    "Palo Verde",
    "Palos Verdes Estates",
    "Paradise",
    "Paramount",
    "Parksdale",
    "Parkway-South Sacramento",
    "Parkwood",
    "Parlier",
    "Pasadena",
    "Patterson",
    "Paxton",
    "Pearsonville",
    "Pedley",
    "Penn Valley",
    "Perris",
    "Petaluma",
    "Phoenix Lake-Cedar Ridge",
    "Pico Rivera",
    "Piedmont",
    "Pine Hills",
    "Pine Mountain Club",
    "Pine Valley",
    "Pinole",
    "Piru",
    "Pismo Beach",
    "Pittsburg",
    "Pixley",
    "Placentia",
    "Placerville",
    "Planada",
    "Pleasant Hill",
    "Pleasanton",
    "Plumas Eureka",
    "Plymouth",
    "Point Arena",
    "Point Reyes Station",
    "Pollock Pines",
    "Pomona",
    "Poplar-Cotton Center",
    "Port Costa",
    "Port Hueneme",
    "Porterville",
    "Portola",
    "Portola Hills",
    "Portola Valley",
    "Poway",
    "Prattville",
    "Prunedale",
    "Quail Valley",
    "Quartz Hill",
    "Quincy",
    "Rail Road Flat",
    "Rainbow",
    "Raisin City",
    "Ramona",
    "Rancho Calaveras",
    "Rancho Cordova",
    "Rancho Cucamonga",
    "Rancho Mirage",
    "Rancho Murieta",
    "Rancho Palos Verdes",
    "Rancho San Diego",
    "Rancho Santa Fe",
    "Rancho Santa Margarita",
    "Rancho Tehama Reserve",
    "Randsburg",
    "Red Bluff",
    "Redding",
    "Redlands",
    "Redondo Beach",
    "Redway",
    "Redwood City",
    "Reedley",
    "Rialto",
    "Richgrove",
    "Richmond",
    "Ridgecrest",
    "Ridgemark",
    "Rio Dell",
    "Rio Linda",
    "Rio Vista",
    "Rio del Mar",
    "Ripon",
    "Riverbank",
    "Riverdale",
    "Riverdale Park",
    "Riverside",
    "Rocklin",
    "Rodeo",
    "Rohnert Park",
    "Rolling Hills",
    "Rolling Hills Estates",
    "Rollingwood",
    "Romoland",
    "Rosamond",
    "Rosedale",
    "Roseland",
    "Rosemead",
    "Rosemont",
    "Roseville",
    "Ross",
    "Rossmoor",
    "Round Mountain",
    "Round Valley",
    "Rowland Heights",
    "Rubidoux",
    "Running Springs",
    "Sacramento",
    "Salida",
    "Salinas",
    "Salton City",
    "Salton Sea Beach",
    "San Andreas",
    "San Anselmo",
    "San Antonio Heights",
    "San Ardo",
    "San Bernardino",
    "San Bruno",
    "San Carlos",
    "San Clemente",
    "San Diego",
    "San Diego Country Estates",
    "San Dimas",
    "San Fernando",
    "San Francisco",
    "San Gabriel",
    "San Geronimo",
    "San Jacinto",
    "San Joaquin",
    "San Joaquin Hills",
    "San Jose",
    "San Juan Bautista",
    "San Juan Capistrano",
    "San Leandro",
    "San Lorenzo",
    "San Lucas",
    "San Luis Obispo",
    "San Marcos",
    "San Marino",
    "San Martin",
    "San Mateo",
    "San Miguel",
    "San Pablo",
    "San Rafael",
    "San Ramon",
    "Sand City",
    "Sanger",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Fe Springs",
    "Santa Maria",
    "Santa Monica",
    "Santa Paula",
    "Santa Rosa",
    "Santa Venetia",
    "Santa Ynez",
    "Santee",
    "Saratoga",
    "Sausalito",
    "Scotts Valley",
    "Seal Beach",
    "Searles Valley",
    "Seaside",
    "Sebastopol",
    "Sedco Hills",
    "Seeley",
    "Selma",
    "Seven Trees",
    "Shackelford",
    "Shafter",
    "Shandon",
    "Shasta Lake",
    "Shaver Lake",
    "Shingle Springs",
    "Shingletown",
    "Shoshone",
    "Sierra Madre",
    "Signal Hill",
    "Simi Valley",
    "Solana Beach",
    "Soledad",
    "Solvang",
    "Sonoma",
    "Sonora",
    "Soquel",
    "Soulsbyville",
    "South Dos Palos",
    "South El Monte",
    "South Gate",
    "South Lake Tahoe",
    "South Oroville",
    "South Pasadena",
    "South San Francisco",
    "South San Gabriel",
    "South San Jose Hills",
    "South Taft",
    "South Whittier",
    "South Woodbridge",
    "South Yuba City",
    "Spreckels",
    "Spring Garden",
    "Spring Valley",
    "Springville",
    "Squaw Valley",
    "Squirrel Mountain Valley",
    "St. Helena",
    "Stallion Springs",
    "Stanford",
    "Stanton",
    "Stinson Beach",
    "Stockton",
    "Storrie",
    "Stratford",
    "Strathmore",
    "Strawberry",
    "Suisun City",
    "Summerland",
    "Sun City",
    "Sunnyside-Tahoe City",
    "Sunnyslope",
    "Sunnyvale",
    "Sunol",
    "Sunol-Midtown",
    "Susanville",
    "Sutter",
    "Sutter Creek",
    "Taft",
    "Taft Heights",
    "Taft Mosswood",
    "Tahoe Vista",
    "Talmage",
    "Tamalpais-Homestead Valley",
    "Tara Hills",
    "Taylorsville",
    "Tecopa",
    "Tehachapi",
    "Tehama",
    "Temecula",
    "Temelec",
    "Temple City",
    "Templeton",
    "Tennant",
    "Terra Bella",
    "Thermalito",
    "Thousand Oaks",
    "Thousand Palms",
    "Three Rivers",
    "Tiburon",
    "Tierra Buena",
    "Tipton",
    "Tobin",
    "Tomales",
    "Toro Canyon",
    "Torrance",
    "Tracy",
    "Tranquillity",
    "Traver",
    "Trinidad",
    "Truckee",
    "Tulare",
    "Tulelake",
    "Tuolumne City",
    "Tupman",
    "Turlock",
    "Tustin",
    "Tustin Foothills",
    "Twain",
    "Twain Harte",
    "Twentynine Palms",
    "Twentynine Palms Base",
    "Twin Lakes",
    "Ukiah",
    "Union City",
    "Upland",
    "Upper Lake",
    "Vacaville",
    "Val Verde",
    "Valinda",
    "Valle Vista",
    "Vallecito",
    "Vallejo",
    "Valley Acres",
    "Valley Center",
    "Valley Ranch",
    "Valley Springs",
    "Vandenberg AFB",
    "Vandenberg Village",
    "Ventura",
    "Vernon",
    "Victorville",
    "View Park-Windsor Hills",
    "Villa Park",
    "Vincent",
    "Vine Hill",
    "Vineyard",
    "Visalia",
    "Vista",
    "Waldon",
    "Wallace",
    "Walnut",
    "Walnut Creek",
    "Walnut Grove",
    "Walnut Park",
    "Wasco",
    "Waterford",
    "Watsonville",
    "Weaverville",
    "Weed",
    "Weedpatch",
    "Weldon",
    "West Athens",
    "West Bishop",
    "West Carson",
    "West Compton",
    "West Covina",
    "West Hollywood",
    "West Menlo Park",
    "West Modesto",
    "West Point",
    "West Puente Valley",
    "West Sacramento",
    "West Whittier-Los Nietos",
    "Westhaven-Moonstone",
    "Westlake Village",
    "Westley",
    "Westminster",
    "Westmont",
    "Westmorland",
    "Westwood",
    "Wheatland",
    "Whitehawk",
    "Whittier",
    "Wildomar",
    "Wilkerson",
    "Williams",
    "Willits",
    "Willow Creek",
    "Willowbrook",
    "Willows",
    "Wilton",
    "Winchester",
    "Windsor",
    "Winter Gardens",
    "Winterhaven",
    "Winters",
    "Winton",
    "Wofford Heights",
    "Woodacre",
    "Woodcrest",
    "Woodlake",
    "Woodland",
    "Woodside",
    "Woodville",
    "Wrightwood",
    "Yorba Linda",
    "Yosemite Lakes",
    "Yosemite Valley",
    "Yountville",
    "Yreka",
    "Yuba City",
    "Yucaipa",
    "Yucca Valley",
].map(function (q) { return q.toUpperCase(); });
